### ISSUE TITLE
first of all why R5 if it dont support most of things for playing game

### ISSUE THREAD

**Issue by Samthapa76** [openmultiplayer/open.mp#1018]
its useless thing i have ever seen why have to update to R5 ? if its not support almost everything no lua no sampfuncs just tell me 1 good reason to keep using it

**Comment by edgyaf** [comment]
Why are you reporting it here instead of to the developers of the modifications to update them to the latest version of the SA-MP client? RCE fixes are reason enough to use the latest version.

**Comment by NexiusTailer** [comment]
First of all the same question but reversed: why anything other than R5?

Anybody doesn't even need to look at outdated stuff which you reffering to, for some reason. If you depend on abandonware shit like "lua and sampfuncs" (or whatever else) which support only ancient client versions, just delete them and call it a day.

Otherwise, downgrade to 0.1b so you won't be infringing on older versions with your logic, ofc if you still not did it yet

**Comment by NexiusTailer** [comment]
Btw noticed only now that a guy opened an issue in omp **server**. I have no doubt it's either a troll or challenged

**Comment by AmyrAhmady** [comment]
You are blocked for ever creating another issue for any open.mp projects, the least you can do is to behave like a normal human being. https://github.com/openmultiplayer/launcher/issues/239#issuecomment-2466677358
And for anyone coming here with the same question, we are not responsible for your shitty mods and cheats with dead development and never getting updates, it's not out fault sampfuncs developer decided to never update it for any version higher than 037 R1. There are ton of security fixes for your own sake. Hope your PC gets hijacked while using R1 so you understand why you need prioritize updating client over your shitty mods. Closing
