### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by Southclaws** [openmultiplayer/open.mp#133]
- logging to a file should be able to be disabled entirely
- logging to a file enabled by default for quick start and simple use-cases
- always write to stdout (not stderr - keeps it simple)
- when enabled, there should be basic log rotation based on day

`logs/2021-08-16.log`

**Comment by AmyrAhmady** [comment]
**Available in next build**

Not gonna add date-based logging by default. (because many hosting services and software/tools parse logs and make data out of it using the timestamp printed/written out)

But being able to specify a file now works, and it can be changed on the fly and calling `reloadlog` rcon cmd

So now a script can rename/change log path config option at runtime and then use `reloadlog` cmd, all programmatically, to their desired way of logging (daily, weekly, monthly, or etc)

The rest of requested enhancements have already been done in previous changes/releases
