### ISSUE TITLE
Players still collide if they enter modshop together with two separate cars

### ISSUE THREAD

**Issue by Mergevos** [openmultiplayer/open.mp#652]

**Comment by AmyrAhmady** [comment]
What do you propose as a fix for this problem?

**Comment by Mergevos** [comment]
> What do you propose as a fix for this problem?

Since it can be done within a script, by, I think, changing players' inside vehicle virtual world. I suggest you to try implementing something like this if possible.

**Comment by AmyrAhmady** [comment]
If you have any script doing the same, it'd be nice if you could share it
so I follow the logic and implement it

**Comment by r4sheed** [comment]
I’ve made a temporary fix for this but we are experienced some strange behavior when leaving the mod shop. If there is a passenger there is a chance the passenger will teleported in Red County (where is the interior is located) with the vehicle, but the driver is still inside the vehicle. It only happened sometimes, maybe because @Mergevos trash internet connection, we could record it on a video. 

You can try to implement a fix on server side using similar method:
```
hook OnEnterExitModShop(playerid, enterexit, interiorid)
{
    new
        vehicleid = GetPlayerVehicleID(playerid);
    if (vehicleid)
    {
        if (enterexit)
        {
            new
                worldid = (playerid + 1);

            SetVehicleVirtualWorld(vehicleid, worldid);
            SetPlayerVirtualWorld(playerid, worldid);

            foreach (new passengerid : VehiclePassenger[vehicleid])
            {
                TogglePlayerControllable(passengerid, false);

                SetPlayerVirtualWorld(passengerid, worldid);
                // SetPlayerInterior(passengerid, interiorid);
                
                // This has no effect
                // SetCameraBehindPlayer(passengerid);
            }

        }
        else
        {
            new
                worldid = 0;

            SetVehicleVirtualWorld(vehicleid, worldid);
            SetPlayerVirtualWorld(playerid, worldid);

            foreach (new passengerid : VehiclePassenger[vehicleid])
            {
                TogglePlayerControllable(passengerid, true);

                SetPlayerVirtualWorld(passengerid, worldid);
                // SetPlayerInterior(passengerid, interiorid);

                // This has no effect
                // SetCameraBehindPlayer(passengerid);
            }
        }
    }

    return 1;
}
```

**Comment by AmyrAhmady** [comment]
Well if it's not reliable as you said then I don't know if we should add it either, we need a proper & reliable way of doing this

**Comment by r4sheed** [comment]
it was happening because the interior was set for the passenger but as you can see it’s commented. Did you even try the code or just wasting my time?

**Comment by AmyrAhmady** [comment]
Nice attitude
Like I said, I'm looking for a reliable logic, by trusting the community to provide us one; So I can implement it natively for everyone and we get to try it and make it go through testing phases

Sorry for wasting your time, closing this issue, hopefully next person with better attitude can be more helpful.

**Comment by r4sheed** [comment]
I’ve provided a code for you which fixed the mentioned issue and you’re refusing to use it because I’ve mentioned ANOTHER issue which is not even related to that code. It’s possibly a client side issue which you should recognize but you just asking for a "reliable way”. There is no reliable way, you can only set virtual worlds to avoid colliding players in mod shops. 

Anyway why did you closed this issue? It’s not even mine, you should fix it instead complaining my attitude. So I have removed my code and good luck fixing it yourself.

**Comment by AmyrAhmady** [comment]
A client side issue is an issue we can not fix at the moment, therefore it's an issue we habe no control over, meaning even if there's a small chance of happening, it is better not to do it at all (it also means it's not reliable)
Whether it's an issue from high ping, or an inconsistency between clients, it's not reliable.

> There is no reliable way

is what you said

My problem was the way you talked when it's a Github issue where people discuss a problem to find the best solution together. Which me calling your code unreliable based on what you said, made you this mad and upset. Now you say I **should** fix it instead of telling you to behave better as a community member. 

If @Mergevos manages to find a proper logic, he can post it here or on discord and I will re-open this issue. right now we are 1:1 to samp. 

Have a nice day. hopefully you will learn how to talk to respectfully one day in places like this :)

**Comment by Mergevos** [comment]
> A client side issue is an issue we can not fix at the moment, therefore it's an issue we habe no control over, meaning even if there's a small chance of happening, it is better not to do it at all (it also means it's not reliable) Whether it's an issue from high ping, or an inconsistency between clients, it's not reliable.
> 
> > There is no reliable way
> 
> is what you said
> 
> My problem was the way you talked when it's a Github issue where people discuss a problem to find the best solution together. Which me calling your code unreliable based on what you said, made you this mad and upset. Now you say I **should** fix it instead of telling you to behave better as a community member.
> 
> If @Mergevos manages to find a proper logic, he can post it here or on discord and I will re-open this issue. right now we are 1:1 to samp.
> 
> Have a nice day. hopefully you will learn how to talk to respectfully one day in places like this :)

Okay @AmyrAhmady, firstly I'm sorry to both of you because of this controversy aforementioned. I hope I'll find a real way of fixing this, hold a numerous of tests and then share a fix, so you can follow the logic. 

Also, is there any plan of open.mp releasing client or any new update?

**Comment by Alasnkz** [comment]
We don't give ETAs on any client releases or updates.
