### ISSUE TITLE
packet not send

### ISSUE THREAD

**Issue by plakapenka** [openmultiplayer/open.mp#669]
pls read is issue for more inf

https://github.com/katursis/Pawn.RakNet/issues/83

**Comment by LitvaMafia** [comment]
This problem is global! Give answer!

**Comment by andreev02** [comment]
Same problem(

**Comment by AmyrAhmady** [comment]
Replied on discord, but I'll write it here as well @plakapenka 

as it was explained in https://github.com/katursis/Pawn.RakNet/issues/83 as well, open.mp's API works a bit differently compared to Pawn.RakNet's enumerators 

Here is something you can try

instead of PR_RELIABLE in your code in here: https://github.com/katursis/Pawn.RakNet/issues/83
since open.mp ignores it, use ordering channel parameter
```cpp
native PR_SendPacket(BitStream:bs, playerid, PR_PacketPriority:priority = PR_HIGH_PRIORITY, PR_PacketReliability:reliability = PR_RELIABLE_ORDERED, orderingchannel = 0);
```

set orderingchannel to 4 and tell me how it goes, like this:
```cpp
PR_SendPacket(bitstream, playerid, PR_SYSTEM_PRIORITY, PR_RELIABLE, 4);
```

**Comment by plakapenka** [comment]
@AmyrAhmady I understand that. But does it make sense for me to do this kind of shit and mess up the code? Will this be fixed by you?

**Comment by plakapenka** [comment]
I would hate to waste time on this fix. And then after you fix it, do it again

**Comment by AmyrAhmady** [comment]
In order to "fix" this we have to make changes in open.mp SDK and API, which means breaking compatibility, not gonna happen anytime soon
Pawn.RakNet was made for samp, not open.mp, it is just a port.
if you want to have a reliable packet sending, just search where you have used PR_RELIABLE and add `4` as ordering channel after that. it's not really that hard

and open.mp does not rely heavily on RakNet, since we might use another networking later in future for clients (currently all of our clients are using RakNet, but I'd like to change that, or use latest fork, SLikeNet)

**Comment by AmyrAhmady** [comment]
Another thing you can do is modifying Pawn.RakNet and pass proper ordering channel to open.mp SDK api when needed, based on what user sets as reliability

**Comment by plakapenka** [comment]
@AmyrAhmady ok. thanks for answers
