### ISSUE TITLE
SetSpawnInfo

### ISSUE THREAD

**Issue by K4rt0** [openmultiplayer/open.mp#699]
can you tell me is the SetSpawnInfo at openmp source error? when i use it and use function SpawnPlayer(playerid); then when 2 objects interact without losing blood, and I used that code for samp source, I don't get the same error.
Thank you so much

**Comment by AmyrAhmady** [comment]
Please elaborate with better English or show us some videos/screenshots

You can also post an MCVE to help us testing it ourselves

**Comment by Vince0789** [comment]
From the discussion in Discord:

It's about the "friendly fire" mechanic with teams. Players in the same team can't damage one another. That is the intended behaviour. OP was specifying `0` for the `teamid` parameter in SetSpawnInfo and since 0 is a valid team, players can't damage each other. That, again, is the intended behaviour.

Suggested using `NO_TEAM` for the `teamid` parameter.
