### ISSUE TITLE
Kick bug, maybe duplicate

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/open.mp#801]
**Describe the bug**
When user get kicked by messageslimit, player start on server online but he is not in game

[2023.12.06 - 18:58:32] [Info] [join] user_name has joined the server (0:ip_address)
[2023.12.06 - 18:59:02] [Warning] client exceeded 'messageslimit' 31.176.176.56:51608 (514) Limit: 500/sec

**To Reproduce**
Spam messages with cheats, idk which exactly

**Commit hash in master**
Release 2 and 3 and every nighly

**Comment by akosd127** [comment]
"When the player exceeds the limit, the following events occur in the game. (see Image 1)
A warning message appears on the console. (see Image 2)
On the server, the player remains active. (see Image 3) The client is no longer needed and can be closed, creating a 'shadow' player.
To remove this lingering player, the ban must be lifted using the 'unbanip' command, followed by reconnecting to the server where an infinite connection attempt will occur.
If the connection attempt fails and the client disconnects, the 'shadow' player is kicked from the server due to a timeout. (see Image 4)"
![1](https://github.com/openmultiplayer/open.mp/assets/15962488/da72f5ac-b280-4b6d-b92a-2fd5b846df96)
![2](https://github.com/openmultiplayer/open.mp/assets/15962488/8c4a01d6-24b3-4eda-a142-99875a1e9ae2)
![3](https://github.com/openmultiplayer/open.mp/assets/15962488/cbc56449-6dbf-45aa-83ba-05197284f31b)
![4](https://github.com/openmultiplayer/open.mp/assets/15962488/1a29fa44-893f-4734-83b6-6bd845e702d4)

**Comment by PazzOnee** [comment]
Fixed in https://github.com/openmultiplayer/open.mp/actions/runs/8556095715, closed
