### ISSUE TITLE
[Suggestion] Server start-up line command

### ISSUE THREAD

**Issue by raiz0x** [openmultiplayer/open.mp#802]
Can you integrate parameters like bind , port , rcon_password , max_players in server start-up command line? This will help providers to protect server.cfg(which should be overwritten with specified parameters in server start-up line)

**Comment by Hual** [comment]
--config already exists

**Comment by raiz0x** [comment]
What --config ? I am new, first time when i see this project, and i didn t found in documentation something about available parameters in start-up line

**Comment by Hual** [comment]
you can consult omp-server.exe --help

  -c, --config arg      Pass (multiple) config option as `option.path=5`

**Comment by raiz0x** [comment]
I need for linux. So i can pass everyting like --config bind "IP" --config port 777 etc ?
And will not be possible to change values from server.cfg ?

**Comment by Hual** [comment]
why don't you test what I suggested before discussing it any further

**Comment by raiz0x** [comment]
because i don't have why to test it if you are unsure

**Comment by Hual** [comment]
testing would have taken you a lot less time than the 20 hours it took me to respond

**Comment by AmyrAhmady** [comment]
Use -h or --help 
You could have done it by now if you were actually willing to try, we are sure, you were given instructions.

**Comment by raiz0x** [comment]
instead of telling me to download and start the server to use 1 or 2 commands, it was better to tell me directly if there are actual arguments that can be used in the startup command line, which is also my question
the question was simple, expecting an equally simple answer, no off-topic
if i wanted to download it and see it i wouldn't have asked
what do i understand there are no starting line commands; there is no documentation; there is no support
my conclusion? i won't use it
you answering in this way, thinking you're 'smart' won't make you smart

**Comment by AmyrAhmady** [comment]
We already said you are able to do this, we gave you an example. But you are refusing to put any further effort yourself. This is not our fault, do not blame your laziness on two people who ALREADY TOLD YOU what you're looking for EXISTS.

You're making absolutely no sense, if you didn't download the package because you were not sure about the possibility of passing config values as CLI args (literally 12 megabytes for your preferred environment, Linux) now you MUST know it's possible. The rest is just you being stubborn. despite resolving the very first blocking problem for you, you still don't want to try anything yourself and fiddle around. Lazy.

This issue will be locked for preventing any further arguments but will be up as an example for everyone that once your initial question is answered and you are shown the path, you have no right to blame those who helped because of your own stubbornness and laziness.
