### ISSUE TITLE
Virtual-Key Codes

### ISSUE THREAD

**Issue by stamenkovicc** [openmultiplayer/open.mp#808]
It would be nice to implement all Virtual Keys. We would get full control over all cheats and more possibilities for some new systems. I know it requires client-side plugin, but I want to leave this here as a reminder.

**Additional context**
https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
![image](https://github.com/openmultiplayer/open.mp/assets/128164307/442c612f-a8c1-4473-abc5-f136e3be04a0)

**Comment by AmyrAhmady** [comment]
It is not going to happen due to various reasons, one being security, like implementing a key logger on user's end.

Also your reason of having this regarding cheat detection makes zero sense because there's no way a cheat is going to send key states to servers when it's being used, so that's out of options.

We will have some other ideas around it, but raw key states is never going to be an option.
