### ISSUE TITLE
GetTickCount return negative value

### ISSUE THREAD

**Issue by Abyss-z94** [openmultiplayer/open.mp#855]
**Describe the bug**
After upgrade my server package to lastest release, i notice that GetTickCount return negative value.

**To Reproduce**
main()
{
	printf("Tick: %d", GetTickCount());
}

**Expected behavior**

**Screenshots and/or logs**
[02/02/2024 21:30:20] [Info] Tick: -1606657016
https://i.imgur.com/SJU788m.png

**Release version**
open.mp 1.2.0.2670

**Comment by NexiusTailer** [comment]
You probably test it under Windows and didn't restart your machine for a couple of weeks (note that I mean exactly 'restart', not turn off/on). Before restarting your PC also try older omp releases and samp server as well, you can ensure the problem doesn't related to open.mp 1.2.0.2670, and then restart the computer and try everything again / see everything is ok since then.

**Comment by Abyss-z94** [comment]
> You probably test it under Windows and didn't restart your machine for a couple of weeks (note that I mean exactly 'restart', not turn off/on). Before restarting your PC also try older omp releases and samp server as well, you can ensure the problem doesn't related to open.mp 1.2.0.2670, and then restart the computer and try everything again / see everything is ok since then.

Thank you, i did not realize that pc still ticking after shutdown.

**Comment by NexiusTailer** [comment]
IIRC it is because of "Fast Startup" option enabled in latest Windows versions.

**Comment by Hual** [comment]
#783 is relevant
